# Generated by Django 5.0.7 on 2024-08-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='is_active',
            new_name='is_staff',
        ),
    ]
