# Generated by Django 5.0.7 on 2024-09-27 18:32

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_active_shopuser_is_staff'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
